title: Jeonghoon ("Jay") Lim
description: Welcome to my personal webpage! This is to introduce myself and my research projects 
show_downloads: true 
github:
  pdf_url: https://github.com/jhlim0918/jhlim0918.github.io/blob/main/docs/Lim_CV.pdf
  repository_url: "https://github.com/jhlim0918/jhlim0918.github.io"

ads_url: "https://ui.adsabs.harvard.edu/search/p_=0&q=orcid%3A%220000-0003-2719-6640%22&sort=date%20desc%2C%20bibcode%20desc"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
